{
  imports = 
    [
      ./direnv.nix
      ./floorp.nix
      ./git.nix
      ./kitty.nix
      ./lutris.nix
      ./niri.nix
      ./polkit-gnome.nix
      ./rofi.nix
      ./starship.nix
      ./swaybg.nix
      ./tmux.nix
      ./trigger.nix
      ./v-analyzer.nix
      ./waybar.nix
      ./winapps.nix
      ./zed.nix
      ./zsh.nix
    ];
}
