{
  imports = 
    [
      ./batsignal.nix
      ./caffeine.nix
      ./cliphist.nix
      ./dconf.nix
      ./dunst.nix
      ./flameshot.nix
      ./flatpak.nix
      ./gtk.nix
      ./joystickwake.nix
      ./keyring.nix
      ./picom.nix
      ./swayidle.nix
      ./xdg.nix
      ./xeventbind.nix
      ./xidlehook.nix
      ./xsettingsd.nix
    ];
}
